### PR TITLE
Make parse-args its own module, add tests

### LINKED ISSUE #19: Transpiler breaks if no args passed
If you try and use the transpiler on a singler source, ie with no --shared option, the task fails as it seems to always expect shared to be provided

```
fs.js:935
  binding.readdir(pathModule._makeLong(path), options.encoding, req);
          ^

TypeError: path must be a string or Buffer
```

### PR DESCRIPTION
**Pull request by roc**
### behold, the beginning of tests

screen shot 2016-09-15 at 10 32 43
- tests arguments are passed in as we expect
- raises question about the importance of the `-w` flag
- use unit tested args parser inside hof-transpiler
### Adds homeoffice eslint config, does some linting ✂️  …
- keeping spaces before function parens but most everything else is maintained
- have cheated on the walker nesting errors, because that is work to do later

fixes #19 
begins #16

### CODE REVIEW

**Comment by joefitter** [comment]
@roc we are using https://github.com/UKHomeOffice/eslint-config-homeoffice for linting hof modules - this includes the eslint executable - if using npm >= 3 you can simply add an npm script 

``` json
"lint": "eslint ."
```

if npm < 3 you will need to point to the path: 

``` json
"lint": "./node_modules/eslint-config-homeoffice/node_modules/.bin/eslint ."
```

This provides 2 base .eslintrc files which can be extended for src and test - see here for examples of both: https://github.com/UKHomeOffice/hmpo-enquiries/blob/master/.eslintrc and https://github.com/UKHomeOffice/hmpo-enquiries/blob/master/test/.eslintrc

**Comment by roc** [comment]
@joefitter added in [38092e8](https://github.com/UKHomeOffice/hof-transpiler/pull/23/commits/38092e82dbf089b0a9781272592db9a4759865f0) but with the odd exception. Not going to try and fix everything in one PR!

File: .eslintignore [hunk 1]
```diff
@@ -0,0 +1,5 @@
+node_modules
+acceptance_tests
+public
+apps/**/translations/**/default.json
```
Comment (JoeChapman) [inline .eslintignore]: don't need this

File: .eslintignore [hunk 2]
```diff
@@ -0,0 +1,5 @@
+node_modules
+acceptance_tests
+public
```
Comment (JoeChapman) [inline .eslintignore]: don't need this

File: bin/hof-transpiler [hunk 3]
```diff
@@ -1,53 +1,39 @@
 #!/usr/bin/env node
 
-var mkdirp = require("mkdirp");
+'use strict';
+
+const parsed = require('../lib/parse-args')(process.argv.slice(2));
+let sources = parsed.sources;
+let shared = parsed.shared;
+
+var mkdirp = require('mkdirp');
```
Comment (JoeChapman) [inline bin/hof-transpiler:9]: const?

File: bin/hof-transpiler [hunk 4]
```diff
@@ -1,53 +1,39 @@
...
 }
 
-_.each(sources, function (src) {
-  var contents = '';
+_.each(sources, function walking (src) {
   var walker = walk.walk(src);
   var writeFileStream = {};
   var firstFileForDir = {};
 
+  /* eslint func-names:0 max-nested-callbacks:0 */
```
Comment (JoeChapman) [inline bin/hof-transpiler:36]: maybe try adding a func name and pulling some of the nested functions out?

File: lib/parse-args.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
+'use strict';
+
+const minimist = require('minimist');
+
+const parse = (args) => {
+  if (!args || args.length === 0) {
+    throw new Error('No src folder or pattern specified');
```
Comment (JoeChapman) [inline lib/parse-args.js:7]: I prefer messages that tell the user how to resolve, maybe "Specify a src folder or pattern"

File: lib/parse-args.js [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+  }
+  const parsed = minimist(args);
+  const writeShared = parsed.writeShared || parsed.w;
+
+  let sources = parsed._;
+  let shared = parsed.s || parsed.shared;
+
+  if (shared && !Array.isArray(shared)) {
+    shared = [shared];
+  }
```
Comment (JoeChapman) [inline lib/parse-args.js:17]: or just `[].concat(shared)`

File: test/lib/parse-args.spec.js [hunk 7]
```diff
@@ -0,0 +1,82 @@
...
+
+        it('shared is an array', () => {
+          result.shared.should.be.an('Array');
+        });
+
+        it('shared is parsed', () => {
+          result.shared.should.deep.equal([
+            'common/**/bar',
+            'common/**/foo'
+            ])
```
Comment (JoeChapman) [inline test/lib/parse-args.spec.js]: indentation and missing semicolon

File: test/lib/parse-args.spec.js [hunk 8]
```diff
@@ -0,0 +1,82 @@
...
+        it('shared is parsed, reversed', () => {
+          result.shared.should.deep.equal([
+            'common/**/bar',
+            'common/**/foo'
+          ])
+        });
+      });
+      describe('with --writeShared', () => {
+
+        it('makes no actual difference to entire thing')
```
Comment (JoeChapman) [inline test/lib/parse-args.spec.js]: what?

File: test/lib/parse-args.spec.js [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+
+        it('shared is an array', () => {
+          result.shared.should.be.an('Array');
+        });
+
+        it('shared is parsed, reversed', () => {
+          result.shared.should.deep.equal([
+            'common/**/bar',
+            'common/**/foo'
+          ])
```
Comment (JoeChapman) [inline test/lib/parse-args.spec.js]: missing semicolon

File: test/lib/parse-args.spec.js [hunk 10]
```diff
@@ -0,0 +1,82 @@
...
+      let result = parse(['foo/**/bar']);
+
+      it('returns sources', () => result.sources.should
+        .deep.equal([ 'foo/**/bar' ]))
+
+      it('shared is undefined', () => {
+        should.not.exist(result.shared);
+      });
+
+      it('throws with array')
```
Comment (JoeChapman) [inline test/lib/parse-args.spec.js]: what?

File: test/lib/parse-args.spec.js [hunk 11]
```diff
@@ -0,0 +1,82 @@
+'use strict';
+
+const parse = require('../../lib/parse-args');
+
+describe('parse-args', () => {
+  describe('no args!', () => {
+    [[],Number(),'',null,undefined].forEach((type) => {
+      it(`${typeof type} '${type}' should throw`, () => {
+        (() => {
+          parse(type)
```
Comment (JoeChapman) [inline test/lib/parse-args.spec.js]: semicolon

File: test/globals.js [hunk 12]
```diff
@@ -0,0 +1,6 @@
+'use strict';
+
+global.chai = require('chai')
+global.should = global.chai.should()
+global.sinon = require('sinon')
+global.proxyquire = require('proxyquire')
```
Comment (JoeChapman) [inline test/globals.js]: missing semicolons

**Review by JoeChapman — CHANGES_REQUESTED** [review]

File: bin/hof-transpiler (hunk 3 above)
Comment (joefitter) [reply bin/hof-transpiler:9]: looks like theres a mix of es5 and es6 - lets leave it all as vars until we es6ify or nuke it

Comment (joefitter) [reply bin/hof-transpiler:9]: I mean update the `let`s above to var

File: test/globals.js (hunk 12 above)
Comment (joefitter) [reply test/globals.js]: do we even want these to be global? Why dont we just require them when we need them?

File: bin/hof-transpiler (hunk 4 above)
Comment (roc) [reply bin/hof-transpiler:36]: Out of scope

File: lib/parse-args.js (hunk 5 above)
Comment (roc) [reply lib/parse-args.js:7]: I'm refactoring to the same spec (same messages). Can improve in another PR

File: test/lib/parse-args.spec.js (hunk 7 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: I'm not linting tests, feel free to add that in a separate PR

File: test/lib/parse-args.spec.js (hunk 8 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: It doesn't, I'm fairly sure we still get a compiled file anyway, and I don't think you can change the destination correctly as is. I would be happy if any other person fancied writing a single other test to disprove

File: test/lib/parse-args.spec.js (hunk 9 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: not linting tests

File: test/globals.js (hunk 12 above)
Comment (roc) [reply test/globals.js]: I find it useful for removing test boilerplate, take them out in a subsequent PR that shows how useful it is not to globalise them if you like

Comment (JoeChapman) [reply test/globals.js]: I think it's typical of our projects @joefitter, but we don't usually make proxyquire gobal.

File: test/lib/parse-args.spec.js (hunk 9 above)
Comment (JoeChapman) [reply test/lib/parse-args.spec.js]: We'd like it if you would

```
extends:
  - '../.eslintrc'
  - 'homeoffice/config/testing'
```

File: bin/hof-transpiler (hunk 3 above)
Comment (roc) [reply bin/hof-transpiler:9]: `mkdirp` looks like a new line because it's bumped down, but my policy (lol) was to add es6 style variable casting for the pieces I was working on. I'll change them all one way or another depending on what you two decide _in another PR_ (or you could, if it's a bother?)

File: test/lib/parse-args.spec.js (hunk 8 above)
Comment (JoeChapman) [reply test/lib/parse-args.spec.js]: ok, but couldn't you remove this line? If you want to raise awareness an issue would be cool.

File: bin/hof-transpiler (hunk 4 above)
Comment (JoeChapman) [reply bin/hof-transpiler:36]: ok

File: test/lib/parse-args.spec.js (hunk 7 above)
Comment (joefitter) [reply test/lib/parse-args.spec.js]: this code has been added so should meet our code style guidelines in order to be merged

File: lib/parse-args.js (hunk 6 above)
Comment (roc) [reply lib/parse-args.js:17]: no, because `shared` is what's being used, `[].concat(shared)` will be a new array. Unless you mean remove the logic and always `concat`, in which case we'll potentially get `[arr, arr]`

File: test/lib/parse-args.spec.js (hunk 8 above)
Comment (joefitter) [reply test/lib/parse-args.spec.js]: writeShared writes the output to the shared directory. It makes no difference to the target directories, but if you are using shared it does (or did) make a difference

Comment (joefitter) [reply test/lib/parse-args.spec.js]: if it is broken please raise an issue

File: lib/parse-args.js (hunk 6 above)
Comment (joefitter) [reply lib/parse-args.js:17]: yes he means the latter, no it will flatten - [].concat([1, 2, 3]) == [1, 2, 3]

File: test/globals.js (hunk 12 above)
Comment (roc) [reply test/globals.js]: Have removed sinon and proxyquire references entirely, as we're not using them yet https://github.com/UKHomeOffice/hof-transpiler/pull/23/commits/9c77d76409b280d2e08972ac9174a78634a032ad

File: test/lib/parse-args.spec.js (hunk 9 above)
Comment (roc) [inline test/lib/parse-args.spec.js]: UGH

File: .eslintignore (hunk 1 above)
Comment (roc) [reply .eslintignore]: changed

File: .eslintignore (hunk 2 above)
Comment (roc) [reply .eslintignore]: don't need this comment now either

**Review by JoeChapman — APPROVED** [review]

File: lib/parse-args.js (hunk 6 above)
Comment (roc) [reply lib/parse-args.js:17]: Yes, but if it's already an array then the call will be `[1,2,3].concat([1, 2, 3]) => [ 1, 2, 3, 1, 2, 3 ]`, unless I'm missing something, in which case, I will fall back to saying: another PR

File: test/lib/parse-args.spec.js (hunk 7 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: @joefitter some things on this:
- okay fine
- add a contributing if you're actually serious about this, otherwise 'what guidelines?'
- okay fine

File: test/lib/parse-args.spec.js (hunk 8 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: I'm not sure it's broken, I'm a confused person adding tests, I can raise an issue re: this though if you like

File: test/lib/parse-args.spec.js (hunk 9 above)
Comment (roc) [reply test/lib/parse-args.spec.js]: fine

File: lib/parse-args.js (hunk 6 above)
Comment (joefitter) [reply lib/parse-args.js:17]: why will it already be an array?

Comment (joefitter) [reply lib/parse-args.js:17]: we are calling `[].concat([1, 2, 3])` or `Array.prototype.concat([1, 2, 3])`

File: test/lib/parse-args.spec.js (hunk 7 above)
Comment (joefitter) [reply test/lib/parse-args.spec.js]: sure, we can add a contributing file, but badly formatted code (indentation) should go without saying

File: test/lib/parse-args.spec.js (hunk 8 above)
Comment (joefitter) [reply test/lib/parse-args.spec.js]: I'd just remove this test for now then
